export const APP_NAME = "T-Solutionz"
export const ALTERNATE_NAME = "TSolutions"
export const BASE_URL = "https://t-solutionz.com"
export const TAGLINE = "Transforming Ideas Into Scalable Systems"
export const BRAND_DESCRIPTION = "T-Solutionz builds modern, scalable software for growing businesses, from web apps to enterprise systems delivering measurable results."